kind: Service
apiVersion: v1
metadata:
  name: webstore-proxy
spec:
  selector:
    app: webstore
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30175
    - port: 443
      targetPort: 443
      nodePort: 30176
