---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstore
  labels:
    app: webstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webstore
  template:
    metadata:
      labels:
        app: webstore
    spec:
      containers:
        - name: webstore
          image: sysztex/alpnginx:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
